# Site settings
title: Vienna PHP User Group
description: ""
url: "http://viennaphp.org"

# Build settings
exclude: ['Rakefile']
timezone: Europe/Vienna
encoding: utf-8
markdown: kramdown
permalink: pretty
